name: secure_key_example
description: Demonstrates how to use the secure_key plugin.
publish_to: "none"

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.2.0
  secure_key:
    path: ../

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
